module.exports = {
    moduleFileExtensions: ['js', 'json', 'ts'],
    rootDir: '..',
    testRegex: String.raw`.*\.spec\.ts$`,
    transform: {
        '^.+\\.(t|j)s$': ['ts-jest', {
            tsconfig: {
                esModuleInterop: true,
                allowSyntheticDefaultImports: true,
            },
        }],
    },
    maxWorkers: 2,
    workerIdleMemoryLimit: '512MB',
    collectCoverageFrom: [
        'apps/**/*.ts',
        'libs/**/*.ts',
        '!apps/**/*.module.ts',
        '!libs/**/*.module.ts',
        '!apps/**/main.ts',
        '!apps/**/config/instrument.ts',
        '!apps/**/migrations/**',
        '!apps/**/dto/**',
        '!apps/**/dtos/**',
        '!libs/**/index.ts',
        '!**/*.config.ts',
        '!**/*.d.ts',
        '!**/*.spec.ts',
        '!**/node_modules/**',
        '!apps/**/scripts/**',
        '!libs/observability/**',
        '!libs/common/src/exceptions/**',
        '!libs/common/src/interceptors/**',
        '!apps/**/database/schema.ts',
        '!apps/**/database/*.schema.ts',
    ],
    coverageDirectory: './coverage',
    testEnvironment: 'node',
    moduleNameMapper: {
        '^@app/common$': '<rootDir>/libs/common/src',
        '^@app/common/(.*)$': '<rootDir>/libs/common/src/$1',
        '^@app/observability$': '<rootDir>/libs/observability/src',
        '^@app/observability/(.*)$': '<rootDir>/libs/observability/src/$1',
        '^@domain/(.*)$': '<rootDir>/apps/transaction-service/src/domain/$1',
        '^@application/(.*)$': '<rootDir>/apps/transaction-service/src/application/$1',
        '^@infrastructure/(.*)$': '<rootDir>/apps/transaction-service/src/infrastructure/$1',
        '^@presentation/(.*)$': '<rootDir>/apps/transaction-service/src/presentation/$1',
    },
    setupFilesAfterEnv: ['<rootDir>/test/setup.ts'],
    testTimeout: 10000,
};
